apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: ti-tempo-instrumentation
spec:
  exporter:
    endpoint: http://opentelemetry-collector.monitoring:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  resource:
    resourceAttributes:
      service.namespace: $(OTEL_COMPONENT)
      environnement: new-environment
      cloud.provider: vcluster
      deployment.environment: pov-ti-tempo
      cadre: $(OTEL_CADRE)

  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.24.0
    env:
      - name: OTEL_COMPONENT
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['component']
      - name: OTEL_CADRE
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['cadre']
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
        value: http://opentelemetry-collector.monitoring:4317
      - name: OTEL_METRICS_EXPORTER
        value: otlp
      - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
        value: http://opentelemetry-collector.monitoring:4317
      
