{
 "title": "OLD - Traces et Métriques RED",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service)(rate(traces_spanmetrics_latency_sum{service=~\".+\"}[1m]) / rate(traces_spanmetrics_latency_count{service=~\".+\"}[1m])) * 55"
    }
   ]
  },
  {
   "title": "Overall Error %age",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\"}[1m]))/sum(increase(traces_spanmetrics_calls_total[1m]))) * 100"
    }
   ]
  },
  {
   "title": "Error Percentages by Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (service)(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",service=~\".*\"}[1m])))/(sum by (service)(increase(traces_spanmetrics_calls_total{status_code!=\"\",service!=\".*\"}[1m]))) * 100",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "Top 10 Highest Service Latencies Over Last Minute",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service)(increase(traces_spanmetrics_latency_sum{service=~\".+\"}[1m]) / increase(traces_spanmetrics_latency_count{service=~\".+\"}[1m])))"
    }
   ]
  },
  {
   "title": "All Endpoint Latencies in ms (Last 10 mins)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "sum by (service)(increase(traces_spanmetrics_latency_sum{service=~\".+\"}[10m]) / increase(traces_spanmetrics_latency_count{service=~\".+\"}[10m]))"
    }
   ]
  },
  {
   "title": "Autologged Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{job=\"agent\"} | logfmt | status=\"STATUS_CODE_ERROR\"",
     "search": "error=true"
    }
   ]
  }
 ]
}
{
 "title": "Traces et Métriques - RED avec Rows",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "environment", "label": "environnement", "query": { "query": "traces_spanmetrics_latency_sum" } },
   {
    "name": "equipe",
    "label": "equipe",
    "query": {
     "query": "traces_spanmetrics_latency_sum{deployment_environment=~\"$environment\"}"
    }
   },
   {
    "name": "cloudprovider",
    "label": "plateforme",
    "query": {
     "query": "traces_spanmetrics_latency_sum{deployment_environment=~\"$environment\", equipe_nom=~\"$equipe\"}"
    }
   },
   {
    "name": "composant",
    "label": "composant",
    "query": {
     "query": "traces_spanmetrics_latency_sum{cloud_provider=~\"$cloudprovider\",deployment_environment=~\"$environment\", equipe_nom=~\"$equipe\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Indicateurs génériques", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Statut du Collecteur",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"opentelemetry-collector\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Statut de Tempo",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"tempo-collector\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total des spans rejetés",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tempo_discarded_spans_total{job=\"tempo-collector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo total des spans reçus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tempo_metrics_generator_spans_received_total{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo total des traces crées par l'ingester",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tempo_ingester_traces_created_total{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo total des Warnings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tempo_warnings_total{instance=\"tempo:3100\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Traces par minutes",
   "type": "timeseries",
   "description": "Transactions (traces)  par minute (Throughput)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum (rate(traces_spanmetrics_calls_total{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[1m]))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Temps passé par span (en %) par heure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (span_name) (avg_over_time(traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}[1m]))*100)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Latences",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Répartition par service",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum by (service)(rate(traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}[1m]) / rate(traces_spanmetrics_latency_count{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}[1m])) * 55",
       "legendFormat": "{{service_namespace}}"
      }
     ]
    },
    {
     "title": "Latence par nom de span",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "avg by (span_name)((traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"})/(traces_spanmetrics_latency_count{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latences de tous les \"Endpoints\" sur les 10 dernières minutes (en ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum by (service)(increase(traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[10m]) / increase(traces_spanmetrics_latency_count{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[10m]))"
      }
     ]
    },
    {
     "title": "Latence par type de span",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "avg by (span_kind)((traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"})/(traces_spanmetrics_latency_count{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}))",
       "legendFormat": "__auto"
      },
      {}
     ]
    },
    {
     "title": "Top 10 latences de service les plus élevées sur les 5 dernières minutes",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(10, sum by (service)(increase(traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[1m]) / increase(traces_spanmetrics_latency_count{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[1m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Erreurs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pourcentage d'erreur global sur la dernière heure",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 9, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",cloud_provider=~\"$cloudprovider\",service_namespace=~\"$composant\", equipe_nom=~\"$equipe\"}[1h]))/sum(increase(traces_spanmetrics_calls_total{cloud_provider=~\"$cloudprovider\",service_namespace=~\"$composant\", equipe_nom=~\"$equipe\"}[1h]))*100)",
       "legendFormat": "Last hour"
      }
     ]
    },
    {
     "title": "Pourcentage d'erreur par \"span\" sur la dernière heure",
     "type": "gauge",
     "description": "taux d'erreur sur la dernière heure",
     "gridPos": { "h": 4, "w": 14, "x": 9, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (span_name)(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",service_namespace=~\"$composant\", equipe_nom=~\"$equipe\"}[1h])))/(sum by (span_name)(increase(traces_spanmetrics_calls_total{status_code!=\"\",service_namespace=~\"$composant\", equipe_nom=~\"$equipe\"}[1h]))*100)",
       "legendFormat": "{{span_name}}"
      }
     ]
    },
    {
     "title": "Pourcentage d'erreur par \"service\" sur la dernière heure",
     "type": "timeseries",
     "description": "taux d'erreur sur la dernière heure",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by (service_namespace)(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",service_namespace=~\"$composant\", equipe_nom=~\"$equipe\"}[1h])))/(sum by (service_namespace)(increase(traces_spanmetrics_calls_total{status_code!=\"\",service_namespace=~\"$composant\", equipe_nom=~\"$equipe\"}[1h])))",
       "legendFormat": "{{service_namespace}}"
      },
      {}
     ]
    },
    {
     "title": "Erreurs totales",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "{job=\"agent\"} | logfmt | status=\"STATUS_CODE_ERROR\"",
       "search": "error=true "
      }
     ]
    }
   ]
  },
  {
   "title": "Exemplars",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latence exemplar",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, (sum (rate(traces_spanmetrics_calls_total{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[1m]))))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(.95, sum(rate(traces_spanmetrics_latency_bucket{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[5m])) by (le, service_namespace))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Traces et Métriques - RED",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "environment", "label": "environnement", "query": { "query": "traces_spanmetrics_latency_sum" } },
   {
    "name": "equipe",
    "label": "equipe",
    "query": {
     "query": "traces_spanmetrics_latency_sum{deployment_environment=~\"$environment\"}"
    }
   },
   {
    "name": "cloudprovider",
    "label": "plateforme",
    "query": {
     "query": "traces_spanmetrics_latency_sum{deployment_environment=~\"$environment\", equipe_nom=~\"$equipe\"}"
    }
   },
   {
    "name": "composant",
    "label": "composant",
    "query": {
     "query": "traces_spanmetrics_latency_sum{cloud_provider=~\"$cloudprovider\",deployment_environment=~\"$environment\", equipe_nom=~\"$equipe\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Traces par minutes",
   "type": "timeseries",
   "description": "Transactions (traces)  par minute (Throughput)",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate(traces_spanmetrics_calls_total{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[1m]))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Pourcentage d'erreur global sur la dernière heure",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",cloud_provider=~\"$cloudprovider\",service_namespace=~\"$composant\", equipe_nom=~\"$equipe\"}[1h]))/sum(increase(traces_spanmetrics_calls_total{cloud_provider=~\"$cloudprovider\",service_namespace=~\"$composant\", equipe_nom=~\"$equipe\"}[1h]))*100)",
     "legendFormat": "Last hour"
    }
   ]
  },
  {
   "title": "Pourcentage d'erreur par \"span\" sur la dernière heure",
   "type": "gauge",
   "description": "taux d'erreur sur la dernière heure",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (span_name)(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",service_namespace=~\"$composant\", equipe_nom=~\"$equipe\"}[1h])))/(sum by (span_name)(increase(traces_spanmetrics_calls_total{status_code!=\"\",service_namespace=~\"$composant\", equipe_nom=~\"$equipe\"}[1h]))*100)",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Répartition par service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (service)(rate(traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}[1m]) / rate(traces_spanmetrics_latency_count{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}[1m])) * 55",
     "legendFormat": "{{service_namespace}}"
    }
   ]
  },
  {
   "title": "Top 10 latences de service les plus élevées sur les 5 dernières minutes",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service)(increase(traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[1m]) / increase(traces_spanmetrics_latency_count{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[1m])))"
    }
   ]
  },
  {
   "title": "Latences de tous les \"Endpoints\" sur les 10 dernières minutes (en ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (service)(increase(traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[10m]) / increase(traces_spanmetrics_latency_count{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[10m]))"
    }
   ]
  },
  {
   "title": "Temps passé par span (en %) par heure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (span_name) (avg_over_time(traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}[1m]))*100)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Latence par type de span",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "avg by (span_kind)((traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"})/(traces_spanmetrics_latency_count{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Latence par nom de span",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "avg by (span_name)((traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"})/(traces_spanmetrics_latency_count{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erreurs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{job=\"agent\"} | logfmt | status=\"STATUS_CODE_ERROR\"",
     "search": "error=true ",
     "serviceName": "${composant}"
    }
   ]
  }
 ]
}
{
 "title": "Tempo Operational",
 "tags": [ "tempo" ],
 "time": { "from": "2022-10-11T07:46:41.889Z", "to": "2022-10-11T15:46:41.889Z" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(tempo_build_info, instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(tempo_build_info,job)"
    }
   },
   {
    "name": "component",
    "query": {
     "query": "label_values(container_network_transmit_bytes_total, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gcs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "go heap",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{ job=~\"$job\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=\"$component\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "working set",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{ container!=\"POD\", pod=~\"$component\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "tx/rx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{ pod=~\"$component\"}[$__rate_interval])",
     "legendFormat": "tx-{{pod}}"
    }
   ]
  },
  {
   "title": "Maintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "%age total work queue",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "tempodb_work_queue_length{job=~\"$job\"} / tempodb_work_queue_max{job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "maintenance errors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(tempodb_compaction_errors_total{ job=~\"$job\"}[$__rate_interval])) by (job)",
       "legendFormat": "compaction_err"
      },
      {
       "expr": "sum(increase(tempodb_retention_errors_total{job=~\"$job\"}[$__rate_interval])) by (job)",
       "legendFormat": "retention_err"
      },
      {
       "expr": "sum(increase(tempodb_blocklist_poll_errors_total{job=~\"$job\"}[$__rate_interval])) by (job)",
       "legendFormat": "blocklist_err"
      }
     ]
    },
    {
     "title": "Blocklist Poll Duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{ job=~\"$job\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempodb_blocklist_poll_duration_seconds_bucket{ job=~\"$job\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Blocklist Length",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(tempodb_blocklist_length{ job=~\"$job\"}) by (tenant)",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "retention duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempodb_retention_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempodb_retention_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempodb_retention_duration_seconds_bucket{ job=~\"$job\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "retention",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(tempodb_retention_deleted_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "deleted"
      },
      {
       "expr": "sum(increase(tempodb_retention_marked_for_deletion_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "marked_for_deletion"
      }
     ]
    },
    {
     "title": "Container Restarts",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
     "targets": [
      {
       "expr": "increase(kube_pod_container_status_restarts_total{}[1d]) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries/Sec (cortex-gw)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\".*api_traces_traceid\",  job=\"$job\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Query Latency (Gateway)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 4, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{ job=\"$job\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{ job=\"$job\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"$job\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Search Queries/Sec (cortex-gw)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\".*api_search.*\", job=\"$job\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Search Query Latency (Gateway)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"$job\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"$job\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"$job\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Queries/Sec (Query Frontend)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\".*api_traces_traceid\", job=\"$job\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Query Latency (Query Frontend)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"$job\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"$job\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"$job\", route=~\".*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Search Queries/Sec (Query Frontend)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tempo_request_duration_seconds_count{ route=~\".*api_search.*\", job=\"$job\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Search Query Latency (Query Frontend)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{ job=\"$job\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"$job\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"$job\", route=~\".*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Queries/Sec (Querier)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\"querier_.*api_traces_traceid\",  job=\"tempo-collector\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Query Latency (Querier)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{job=\"$job\", route=~\"querier_.*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{ job=\"$job\", route=~\"querier_.*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{ job=\"$job\", route=~\"querier_.*api_traces_traceid\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Search Queries/Sec (Querier)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\"querier_.*api_search.*\", job=\"$job\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Search Query Latency (Querier)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{ job=\"$job\", route=~\"querier_.*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{ job=\"$job\", route=~\"querier_.*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{ job=\"$job\", route=~\"querier_.*api_search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Queries/Sec (Ingester)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tempo_request_duration_seconds_count{route=\"/tempopb.Querier/FindTraceByID\", job=\"tempo-collector\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Query Latency (Ingester)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 4, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{ job=\"$job\", route=\"/tempopb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{ job=\"$job\", route=\"/tempopb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"$job\", route=\"/tempopb.Querier/FindTraceByID\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Search Queries/Sec (Ingester)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tempo_request_duration_seconds_count{route=~\"/tempopb.Querier/Search.*\", job=\"$job\"}[$__rate_interval])) by (status_code)",
       "legendFormat": "{{status_code}}",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Search Query Latency (Ingester)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{ job=\"$job\", route=~\"/tempopb.Querier/Search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".99",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{job=\"$job\", route=~\"/tempopb.Querier/Search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".9",
       "stepMode": "min"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"$job\", route=~\"/tempopb.Querier/Search.*\"}[$__rate_interval])) by (le))",
       "legendFormat": ".5",
       "stepMode": "min"
      }
     ]
    }
   ]
  },
  { "title": "Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Spans Received",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(tempo_distributor_spans_received_total{}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Traces Created",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(tempo_ingester_traces_created_total{}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Blocks Flushed (1h)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(tempo_ingester_blocks_flushed_total{job=\"$job\"}[1h]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed Flushes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(tempo_ingester_failed_flushes_total{}[5m]) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Blocks Cleared (1h)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(tempo_ingester_blocks_cleared_total{}[1h]))"
    }
   ]
  },
  {
   "title": "Flush Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_ingester_flush_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_ingester_flush_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_ingester_flush_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Pushes/sec (gateway)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_request_duration_seconds_count{ job=\"$job\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "OTEL Distributor Spans/second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_receiver_accepted_spans{}[$__rate_interval]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(rate(tempo_receiver_refused_spans{}[$__rate_interval]))",
     "legendFormat": "refused"
    }
   ]
  },
  {
   "title": "Push Latency (Gateway)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{}[$__rate_interval])) by (route))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{ job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Push Latency (Ingester)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(tempo_request_duration_seconds_bucket{ job=\"$job\", route=~\"/tempopb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(tempo_request_duration_seconds_bucket{ job=\"$job\", route=~\"/tempopb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(tempo_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", job=\"$namespace/ingester\", route=~\"/tempopb.Pusher/Push.*\"}[$__rate_interval])) by (le))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Memcached",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests/Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(cortex_consul_request_duration_seconds_count{ job=~\"$job\"}[$__rate_interval])) by (status_code, method)",
       "legendFormat": "{{status_code}}-{{method}}"
      }
     ]
    },
    {
     "title": "Latency By Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_consul_request_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (method, le))",
       "legendFormat": ".99-{{method}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_consul_request_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (method, le))",
       "legendFormat": ".9-{{method}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_consul_request_duration_seconds_bucket{ job=~\"$job\"}[$__rate_interval])) by (method, le))",
       "legendFormat": ".5-{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests/Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tempodb_backend_request_duration_seconds_count{ job=~\"$job\"}[$__rate_interval])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    },
    {
     "title": "Latency By Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(tempodb_backend_request_duration_seconds_bucket{ job=~\"$job\"}[$__rate_interval])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(tempodb_backend_request_duration_seconds_bucket{ job=~\"$job\"}[$__rate_interval])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(tempodb_backend_request_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compactor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Objects Combined / s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tempodb_compaction_objects_combined_total{job=~\"$job\"}[$__rate_interval])) by (level)"
      }
     ]
    },
    {
     "title": "Objects Written / s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tempodb_compaction_objects_written_total{job=\"$job\"}[$__rate_interval])) by (level)"
      }
     ]
    },
    {
     "title": "Bytes Written / s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(tempodb_compaction_bytes_written_total{job=\"$job\"}[$__rate_interval])) by (level)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Blocks Compacted",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(tempodb_compaction_blocks_total{job=\"$job\"}[5m])) by (level)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Tempo / Resources",
 "tags": [ "Tempo" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "2h",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Container TEMPO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=~\"monitoring\",container=\"tempo\"}[$__interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{namespace=~\"monitoring\",container=\"tempo\"} / container_spec_cpu_period{namespace=~\"monitoring\",container=\"tempo\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=~\"monitoring\",container=\"tempo\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{namespace=~\"monitoring\",container=\"tempo\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Sum Heap Alloc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (go_gc_heap_allocs_by_size_bytes_total_sum)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tempo Ingester Prometheus Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ingester bytes received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tempo_ingester_bytes_received_total{instance=\"tempo:3100\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Tempo ingestor bytes received total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tempo_ingester_bytes_received_total{instance=\"tempo:3100\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TempodB backend bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tempodb_backend_bytes_total{instance=\"tempo:3100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Spans received Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "tempo_metrics_generator_spans_received_total{instance=\"tempo:3100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "OpenTelemetry - Traces et Métriques - RED / Loki",
 "tags": [
  "OpenTelemetry",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "environnement",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_sum,deployment_environment)"
    }
   },
   {
    "name": "equipe",
    "label": "equipe",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_sum{deployment_environment=~\"$environment\"},equipe_nom)}"
    }
   },
   {
    "name": "cloudprovider",
    "label": "plateforme",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_sum{deployment_environment=~\"$environment\", equipe_nom=~\"$equipe\"},cloud_provider)"
    }
   },
   {
    "name": "composant",
    "label": "composant",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_sum{cloud_provider=~\"$cloudprovider\",deployment_environment=~\"$environment\", equipe_nom=~\"$equipe\"},service_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests (period)",
   "type": "stat",
   "description": "This is the total number of requests made in this period (top-right period selected)",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(otel_metrics_http_server_requests_max{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}[${__range_s}s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 1/2xx (2m)",
   "type": "stat",
   "description": "This is the number of successful requests in the last minute.  Successful being 1xx or 2xx by the standard HTTP definition.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(otel_metrics_http_server_requests_max{status=~\"(1|2).*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 3xx (2m)",
   "type": "stat",
   "description": "This is the number of 3xx requests in the last minute.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(otel_metrics_http_server_requests_max{status=~\"3.*\", service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}[$__interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 4xx (2m)",
   "type": "stat",
   "description": "This is the number of 4xx requests in the last minute.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(otel_metrics_http_server_requests_max{status=~\"4.*\", service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5xx (2m)",
   "type": "stat",
   "description": "This is the number of 5xx requests in the last minute.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(otel_metrics_http_server_requests_max{status=~\"5.*\", service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "description": "The breakdown of the various HTTP status codes of the requests handled within' this period that matches the variables chosen above.\n",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(otel_metrics_http_server_requests_max{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}[1h]))  by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre total de logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": " sum(count_over_time(({service_namespace=~\"$composant\"} )[$__interval]))"
    }
   ]
  },
  {
   "title": "Nombre total d'erreurs dans les logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({service_namespace=~\"$composant\", level=\"ERROR\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "Pourcentage d'erreur global sur la dernière heure",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",cloud_provider=~\"$cloudprovider\",service_namespace=~\"$composant\", equipe_nom=~\"$equipe\"}[1h]))/sum(increase(traces_spanmetrics_calls_total{cloud_provider=~\"$cloudprovider\",service_namespace=~\"$composant\", equipe_nom=~\"$equipe\"}[1h]))*100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de logs par niveaux par composants - Loki",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(count_over_time({service_namespace=~\"$composant\"}[15m])) by (level, service_namespace)"
    }
   ]
  },
  {
   "title": "Pourcentage d'erreur par \"Endpoints\" sur la dernière heure",
   "type": "gauge",
   "description": "taux d'erreur sur la dernière heure",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (span_name)(increase(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",service_namespace=~\"$composant\", equipe_nom=~\"$equipe\"}[1h])))/(sum by (span_name)(increase(traces_spanmetrics_calls_total{status_code!=\"\",service_namespace=~\"$composant\", equipe_nom=~\"$equipe\"}[1h]))*100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence (metriques)",
   "type": "timeseries",
   "description": "The breakdown of the various HTTP status codes of the requests handled within' this period that matches the variables chosen above.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum by (service_namespace)(rate(otel_metrics_http_server_requests_bucket{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}[5m]))",
     "legendFormat": "{{service_namespace}}"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{service_namespace=~\"$composant\"}"
    }
   ]
  },
  {
   "title": "Top 10 latences de service les plus élevées sur les 5 dernières minutes",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, sum by (service)(increase(traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[1m]) / increase(traces_spanmetrics_latency_count{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces par minutes",
   "type": "timeseries",
   "description": "Transactions (traces)  par minute (Throughput)",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum (rate(traces_spanmetrics_calls_total{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Répartition (rate) par service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (service)(rate(traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}[1m]) / rate(traces_spanmetrics_latency_count{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}[1m])) * 55",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latences par Services sur les 15 dernières minutes (en ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by (service)(increase(traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[15m]) / increase(traces_spanmetrics_latency_count{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\", equipe_nom=~\"$equipe\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence par Endpoints sur les 15 dernières minutes (en ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "avg by (span_name)((traces_spanmetrics_latency_sum{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"})/(traces_spanmetrics_latency_count{service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erreurs totales par Services et Endpoints",
   "type": "table",
   "description": "Errerurs reportées sur les 15 dernières minutes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",service_namespace=~\"$composant\",deployment_environment=~\"$environment\", cloud_provider=~\"$cloudprovider\",equipe_nom=~\"$equipe\"}"
    }
   ]
  },
  {
   "title": "Sélectionnez un composant pour voir ses erreurs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "{job=\"agent\"} | logfmt | status=\"STATUS_CODE_ERROR\"",
     "search": "status.code=error",
     "serviceName": "${composant}"
    }
   ]
  },
  {
   "title": "Loki - Erreurs sur logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "{service_name=~\"$composant\", level=\"ERROR\"}| json | line_format \"{{.log}}\" "
    }
   ]
  }
 ]
}
{
 "title": "Benchmark2",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage No Agent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\",namespace=~\"quarkus-no-agent\"}[2m])) by (pod) / (sum(container_spec_cpu_quota{container !=\"\",container!=\"POD\",namespace=~\"quarkus-no-agent\"}/100000) by (pod)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage  Opentelemetry",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\",namespace=~\"quarkus-otel\"}[2m])) by (pod) / (sum(container_spec_cpu_quota{container !=\"\",container!=\"POD\",namespace=~\"quarkus-otel\"}/100000) by (pod)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage  AppDyn",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\",namespace=~\"quarkus-appdyn\"}[2m])) by (pod) / (sum(container_spec_cpu_quota{container !=\"\",container!=\"POD\",namespace=~\"quarkus-appdyn\"}/100000) by (pod)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage  Double",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\",namespace=~\"quarkus-double\"}[2m])) by (pod) / (sum(container_spec_cpu_quota{container !=\"\",container!=\"POD\",namespace=~\"quarkus-double\"}/100000) by (pod)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Quarkus No Agent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"quarkus-no-agent\", container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Quarkus Opentelemetry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"quarkus-otel\", container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Quarkus AppDyn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"quarkus-appdyn\", container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Quarkus Double",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"quarkus-double\", container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Percentage Memory Quarkus No Agent",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_rss{container !=\"\",namespace=~\"quarkus-no-agent\"}) by ( pod)/ sum(container_spec_memory_limit_bytes{container !=\"\",namespace=~\"quarkus-no-agent\"}) by (pod) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Percentage Memory Quarkus Opentelemetry",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_rss{container !=\"\",namespace=~\"quarkus-otel\"}) by ( pod)/ sum(container_spec_memory_limit_bytes{container !=\"\",namespace=~\"quarkus-otel\"}) by (pod) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Percentage Memory Quarkus AppDyn",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_rss{container !=\"\",namespace=~\"quarkus-appdyn\"}) by ( pod)/ sum(container_spec_memory_limit_bytes{container !=\"\",namespace=~\"quarkus-appdyn\"}) by (pod) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Percentage Memory Quarkus Double",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_rss{container !=\"\",namespace=~\"quarkus-double\"}) by ( pod)/ sum(container_spec_memory_limit_bytes{container !=\"\",namespace=~\"quarkus-double\"}) by (pod) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}